################################# Default configuration ###################
baseURL = "https://ram-ev.netlify.app"
title = "RAM e.V."
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


################### German Navigation ########################
[[Languages.de.menu.main]]
name = "Über uns"
url = "#about"
weight = 1

[[Languages.de.menu.main]]
HasChildren = true
  [[Languages.de.menu.main]]
  parent = "Über uns"
  name = "Mehr über RAM e.V."
  url = "/de/about/mehr_ueber_ram"
  weight = 1

  [[Languages.de.menu.main]]
  parent = "Über uns"
  name = "Satzung"
  url = "/de/about/satzung"
  weight = 2
  
  [[Languages.de.menu.main]]
  parent = "Über uns"
  name = "Datenschutzordnung"
  url = "/de/about/imprint"
  weight = 3
  
  [[Languages.de.menu.main]]
  parent = "Über uns"
  name = "Datenschutzerklärung"
  url = "/de/about/privacy_policy"
  weight = 4
  
  [[Languages.de.menu.main]]
  parent = "Über uns"
  name = "Impressum"
  url = "/de/about/impressum"
  weight = 5
  
  [[Languages.de.menu.main]]
  parent = "Über uns"
  name = "Kontakt"
  url = "/de/about/contact"
  weight = 6

[[Languages.de.menu.main]]
name = "Geförderte Forschungsprojekte"
url = "#portfolio"
weight = 2

[[Languages.de.menu.main]]
name = "Förderung"
url = "#pricing"
weight = 3

[[Languages.de.menu.main]]
HasChildren = true
  [[Languages.de.menu.main]]
  parent = "Förderung"
  name = "Übersicht"
  url = "/de/funding/funding-uebersicht"
  weight = 1
  
  [[Languages.de.menu.main]]
  parent = "Förderung"
  name = "Normalförderung"
  url = "/de/funding/normalfoerderung"
  weight = 2
  
  [[Languages.de.menu.main]]
  parent = "Förderung"
  name = "Rationale Altruisten Travel Grant"
  url = "/de/funding/rat-grant"
  weight = 3
  
  [[Languages.de.menu.main]]
  parent = "Förderung"
  name = "Preise"
  url = "/de/funding/preise"
  weight = 4
  
[[Languages.de.menu.main]]
name = "Mitglied werden"
url = "de/mitglied/mitglied-werden"
weight = 4

[[Languages.de.menu.main]]
name = ""
url = "#testimonials"
weight = 5

[[Languages.de.menu.main]]
name = "Aktuelles"
url = "#blog"
weight = 6

[[Languages.de.menu.main]]
name = ""
url = "#team"
weight = 7

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 4

[[Languages.en.menu.main]]
name = "pricing"
url = "#pricing"
weight = 5

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7

[[Languages.en.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = ""
author = "RAM e.V."
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/ram.ev"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "http://instagram.com/rationale.altruisten/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/ram_ev"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/ram-ev/'"

[[params.social]]
icon = "ti-email" # themify icon pack : https://themify.me/themify-icons
link = "mailto:vorstand@ram-ev.de"

################################ German Language ########################
[Languages.de]
languageName = "Deutsch"
languageCode = "de-de"
contentDir = "content/deutsch"
weight = 1
home = "Über uns"
copyright = "Copyright &copy; 2021 Rationale Altruisten Mannheim e.V."

################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2021 Rationale Altruisten Mannheim e.V."

